version: '3.7'

services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server
    environment: 
      ACCEPT_EULA: "Y" 
      SA_PASSWORD: "Password_01"
    ports:
      - "1433:1433"
  grouplinkapi:
    build: ./GroupLinkApi
    environment: 
      DBServer: "ms-sql-server"
    ports:
      - "8080:80"
    depends_on: 
      - ms-sql-server

  grouplink-web:
    container_name: grouplink-web
    build: ./GroupLinkWeb/grouplink-app
    volumes:
      - '.:/GroupLinkWeb/grouplink-app/usr/src/app'
      - '/GroupLinkWeb/grouplink-app/usr/src/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on: 
      - grouplinkapi




